### ISSUE TITLE
'?dl=0' does not work with dropbox links

### ISSUE THREAD

**Issue by kmader** [akeshavan/mindcontrol#24]
Part of the qc.js code appends a `?dl=0` do the URL, is that necessary? It causes problems from dropbox links since they must end it `?dl=1` from them to be downloaded (https://github.com/akeshavan/mindcontrol/blob/9aeecc70646cb61be7024e3e4b038a4d3609175f/imports/ui/qc.js#L75)

**Comment by akeshavan** [comment]
Thanks for catching this! I've just pushed a change deleting that hardcoded part

**Comment by kmader** [comment]
thanks: https://github.com/akeshavan/mindcontrol/commit/aa80efdc5333f0136155f5e304eb55fd02834afb
