### ISSUE TITLE
fill_all_points function not defined

### ISSUE THREAD

**Issue by kmader** [akeshavan/mindcontrol#25]
The client throws an error about the definition of this function periodically, it appears to be defined.

https://github.com/akeshavan/mindcontrol/blob/9aeecc70646cb61be7024e3e4b038a4d3609175f/imports/ui/qc.js#L809

Maybe it has been replaced with code like this: 
```
template.contours.set(points)
papayaContainers[0].viewer.drawViewer(true) //fill_all(template)
```

**Comment by kmader** [comment]
It also does not appear to be a standard library function at all https://github.com/search?l=JavaScript&q=fill_all_points&type=Code&utf8=%E2%9C%93

**Comment by akeshavan** [comment]
Yep, that function no longer exists. I've just pushed a change removing that, and it seems logging contours still works as expect. Thanks!

**Comment by kmader** [comment]
thanks https://github.com/akeshavan/mindcontrol/commit/741dd720b2d09f29a9186b7ddc9be2c9ef40c213
